services:
  frontend:
    container_name: frontend
    build:
      context: .
      target: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - buzzer-network
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: .
    
      target: backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:////data/db.sqlite
    networks:
      - buzzer-network
    restart: unless-stopped
    volumes:
      - sqlite-data:/data

networks:
  buzzer-network:
    driver: bridge

volumes:
  backend-logs:
  sqlite-data: