version: '3.8'

services:
  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - buzzer-network
    restart: unless-stopped

  backend:
    build:
      context: .
      target: backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - buzzer-network
    restart: unless-stopped
    volumes:
      - backend-logs:/app/backend/logs

networks:
  buzzer-network:
    driver: bridge

volumes:
  backend-logs: